#!/usr/bin/env bash
# A part of Elten - EltenLink / Elten Network desktop client.
# Copyright (C) 2026 Dawid Pieper
# Elten is free software: GNU General Public License v3.
#
# Build Elten's native C-extension gems for iOS and stage them next to the CRuby
# runtime. Registered in ruby_shim.c with ruby_init_ext (static extensions;
# iOS forbids dlopen of external dylibs).
#
# VERIFIED on the iOS simulator (arm64), all requiring + exercising cleanly:
#   * bigdecimal 3.3.1   (pure C)
#   * zstd-ruby 2.0.6    (bundled libzstd)
#   * nokogiri 1.19.4    (links the SDK's libxml2 + libxslt; gumbo bundled)
# Pure-Ruby gems need NO build (bundle their lib/ only):
#   * ruby-xz 1.0.3      (Fiddle -> the system liblzma in the iOS dyld cache)
#   * rubyzip 3.2.2, http-2, base62, base64, ostruct
#
# Usage: SDK=iphonesimulator ARCH=arm64 ./build-gems-ios.sh
set -euo pipefail

SDK="${SDK:-iphonesimulator}"; ARCH="${ARCH:-arm64}"; MIN_IOS="${MIN_IOS:-16.0}"
RUBY_VERSION="${RUBY_VERSION:-4.0.4}"     # match the CRuby runtime
IOS_DIR="$(cd "$(dirname "$0")/.." && pwd)/Elten"
INC_RUBY="$IOS_DIR/vendor/cruby/include"
OUT="$IOS_DIR/vendor/gems/$SDK-$ARCH"
WORK="${WORK:-$(mktemp -d)}"
[ -d "$INC_RUBY" ] || { echo "!! run fetch-cruby-runtime.sh first"; exit 1; }

SDKROOT="$(xcrun --sdk "$SDK" --show-sdk-path)"; CLANG="$(xcrun --sdk "$SDK" -f clang)"
[ "$SDK" = iphonesimulator ] && TARGET="${ARCH}-apple-ios${MIN_IOS}-simulator" || TARGET="${ARCH}-apple-ios${MIN_IOS}"
BASE=(-target "$TARGET" -isysroot "$SDKROOT" -O2 -fno-common)
mkdir -p "$OUT"; cd "$WORK"
gem_src() { local s="$1"; curl -fsSLO "https://rubygems.org/downloads/$s.gem"; mkdir -p "$s"; tar xf "$s.gem" -C "$s"; tar xzf "$s/data.tar.gz" -C "$s"; }

# --- bigdecimal ------------------------------------------------------------
gem_src bigdecimal-3.3.1
BD="$WORK/bigdecimal-3.3.1/ext/bigdecimal"
BDDEFS=(-DHAVE_FLOAT_H -DHAVE_MATH_H -DHAVE_STDBOOL_H -DHAVE_STDLIB_H \
  -DHAVE_RUBY_ATOMIC_H -DHAVE_RUBY_INTERNAL_HAS_BUILTIN_H -DHAVE_RUBY_INTERNAL_STATIC_ASSERT_H \
  -DHAVE_RB_COMPLEX_REAL -DHAVE_RB_COMPLEX_IMAG -DHAVE_RB_OPTS_EXCEPTION_P \
  -DHAVE_RB_CATEGORY_WARN -DHAVE_RB_EXT_RACTOR_SAFE \
  -DHAVE_BUILTIN___BUILTIN_CLZ -DHAVE_BUILTIN___BUILTIN_CLZL -DHAVE_BUILTIN___BUILTIN_CLZLL \
  -DHAVE_BUILTIN___BUILTIN_ADD_OVERFLOW -DHAVE_BUILTIN___BUILTIN_MUL_OVERFLOW)
mkdir -p o; rm -f o/*
for s in "$BD/bigdecimal.c" "$BD/missing.c"; do
  "$CLANG" "${BASE[@]}" "${BDDEFS[@]}" -I"$INC_RUBY" -I"$BD" -c "$s" -o "o/$(basename "$s" .c).o"; done
xcrun ar rcs "$OUT/libbigdecimal.a" o/*.o

# --- zstd-ruby -------------------------------------------------------------
gem_src zstd-ruby-2.0.6
Z="$WORK/zstd-ruby-2.0.6/ext/zstdruby"
mkdir -p oz; rm -f oz/*
ZI=(-I"$Z" -I"$Z/libzstd" -I"$Z/libzstd/common" -I"$Z/libzstd/compress" -I"$Z/libzstd/decompress" -I"$Z/libzstd/dictBuilder" -I"$INC_RUBY")
for s in $(find "$Z/libzstd" -name '*.c') "$Z"/*.c; do
  "$CLANG" "${BASE[@]}" -std=c99 -DZSTD_STATIC_LINKING_ONLY -DZSTD_MULTITHREAD -DDEBUGLEVEL=0 -fvisibility=hidden \
    "${ZI[@]}" -c "$s" -o "oz/$(echo "$s"|md5 -q).o"; done
xcrun ar rcs "$OUT/libzstdruby.a" oz/*.o

# --- nokogiri (system libxml2 + libxslt) -----------------------------------
gem_src nokogiri-1.19.4
N="$WORK/nokogiri-1.19.4"
# libxslt headers (xsltconfig.h is generated by configure); link the SDK libs.
curl -fsSLO "https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.39.tar.xz"
tar xf libxslt-1.1.39.tar.xz
( cd libxslt-1.1.39 && ./configure --without-python --without-crypto >/dev/null 2>&1 )
XSLT="$WORK/libxslt-1.1.39"; GUMBO="$N/gumbo-parser/src"
mkdir -p on; rm -f on/*
NI=(-I"$INC_RUBY" -I"$N/ext/nokogiri" -I"$GUMBO" -I"$SDKROOT/usr/include/libxml2" -I"$XSLT")
for s in "$N/ext/nokogiri"/*.c "$GUMBO"/*.c; do
  "$CLANG" "${BASE[@]}" -std=c99 "${NI[@]}" -c "$s" -o "on/$(echo "$s"|md5 -q).o"; done
xcrun ar rcs "$OUT/libnokogiri.a" on/*.o

echo "==> Built gem archives in $OUT:"
for a in libbigdecimal libzstdruby libnokogiri; do echo "    $a.a"; done
cat <<'NOTE'

Register in ruby_shim.c after CRuby_init:
  ruby_init_ext("bigdecimal.so", Init_bigdecimal);
  ruby_init_ext("zstd-ruby/zstdruby.so", Init_zstdruby);
  ruby_init_ext("nokogiri/nokogiri.so", Init_nokogiri);
Link -lxml2 -lxslt -lexslt for nokogiri. Set CRUBY_BUILD_SDK_AND_ARCH before
loading (e.g. 'iphonesimulator-arm64') so rbconfig resolves. Bundle each gem's
lib/ and the CRuby lib/ruby (4.0.0 + rbconfig on $LOAD_PATH).
NOTE
