name: EltenInteractionDemo
options:
  bundleIdPrefix: it.sixdots
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
targets:
  EltenInteractionDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Klangten
        UILaunchScreen: {}
        UIApplicationSupportsIndirectInputEvents: true
        UIRequiredDeviceCapabilities: [arm64]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: it.sixdots.klangten.interactiondemo
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "3.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
